### ISSUE TITLE
Prepare and Conduct Program Increment Planning

### ISSUE THREAD

**Issue by jamesmrollins** [jamesmrollins/CIDMO_LCMT#13]
## Description
For CIDMO teams responsible for delivering IHP solutions, the Program Increment Planning Conference (PIPC) is a week-long virtual event held each quarter that enables integrated teams to scope and coordinate work in order set expectations for a solution delivery schedule.  

Unlike the current IHP process that requires CIDMO divisions to independently resource each IPT in sequence, the PIPC will enable cross-divisional resources (dedicated to supporting IHPs) to create their plans for delivering high-priority, high-impact solutions.  

### Minimally Viable Product
A minimally viable product will include:
1. Specified purpose and business outcomes from PIPCs for IHP work 
2. The execution of a PIPC for three clinical value streams
3. Guidance and tools for CIDMO to conduct quarterly PIPCs 

### Business Outcomes
TBD

### Planning 
- [ ] Engage OIT consultants to help develop CIDMO capabilities to successfully conduct a PIP conference.
- [ ] Define objectives, inputs, and outputs for a PIPC 
- [ ] Secure the tooling required to carry out a PIPC 
- [ ] Deliver a PIPC Toolkit that describes roles, activities, and tools for PI Planning
### Simulation 
- [ ] Identify a single-team use case (to conduct a single-team event or walk through the process)  
- [ ] Conduct a single-team PIPC or simulate the PIPC process 
### Execution
- [ ] Establish a PI Planning Conference Date 
- [ ] Identify the three IHP work efforts (and role assignments) for the PIPC 
- [ ] Provide role-based training to PIPC participants 
- [ ] Carry out a Program Increment Planning Conference 

## Risks
- Because of the importance of PI Planning and the complexity associated with planning/coordinating work across teams, it is best practice to carry out PIPCs as an in-person event. CIDMO PIPCs will have to be carried out virtually. 
- In the first PIPC, CIDMO teams are expected to plan their work in an Agile process that will be new to them.
