### ISSUE TITLE
Develop Training

### ISSUE THREAD

**Issue by jamesmrollins** [jamesmrollins/CIDMO_LCMT#6]
This epic manages all necessary training development activities needed to stand up an Agile Team.

# Curriculum Topics

The list below provides a knowledge-based competency guide to develop Agile Teams.  The guide contains a listing of topic areas that will be further described in related cards. 

## Required Competencies

Upon completion of training, an Agile Team will have the following knowledge necessary to manage their team using Scrum methodologies, GitHub, and ZenHub management systems.

### Understand Lean-Agile Development

- [x] Understand and relate lean-agile terms, acronyms and principles.
- [x] Understand value streams and how development value streams support clinical value streams.
- [x] Understand the role of the Agile Release Train and how they fulfill product and service requests.
- [x] Understand how product portfolios are prioritized by the IHPMB and sent to Agile Release Trains for development.
- [ ] Understand how the organization will use cadence to enhance flow, planning and task execution.

### Set Up a Development Value Stream

- [x] Understand how our individual work is going to fundamentally change.
- [x] Know how to fill out a value stream canvas.
- [x] Know how to make a value stream map and use it define how and the standards to which work will be performed.
- [x] Understand the relationship between the value stream and managing value stream improvement activities.

### Manage a Data/Code/Document Repository in GitHub

- [ ] Set up a GitHub user account and invite others to the Srum.
- [ ] Create an issue and properly apply labels, assignments and story point estimates.
- [ ] Create a branch system to manage versions of work and establish quality control.
- [ ] Use a repository to store data/code/documents.

### Manage Scrums with ZenHub

- [ ] Organize and participate in a daily Scrum.
- [ ] Set up a user account in ZenHub.
- [ ] Create issue cards and use to manage asynchronous discussions, links, screen captures and demonstration projects. 
- [ ] Use ZenHub to manage work through daily Scrums (epics, sprints and estimates).
- [ ] Report progress using ZenHub.

### Participate in Program Increment Planning

- [x] Understand the purpose and objectives for Program Increment Planning (PIP).
- [x] Adequately prepare for a PIP conference by bringing necessary materials and reading ahead.
- [x] Participate in PIP planning activities.
- [x] Estimate sprint activities and evaluate risk to completing activities during the covered PIP period.
- [x] Evaluate team performance during prior PIP period and determine improvement steps for team and ART performance.

**Comment by maneyb1** [comment]
Add training to IWS list: https://dvagov.sharepoint.com/sites/VHACIDMO/CIDMO_FIS/IWS/ICP_WG/IWS-HICP/FDER/Forms/AllItems.aspx?id=%2Fsites%2FVHACIDMO%2FCIDMO%5FFIS%2FIWS%2FICP%5FWG%2FIWS%2DHICP%2FFDER%2FHealth%5FInformatics%5Fand%5FData%5FAnalytics%5FTraining%5FResources%2Epdf&parent=%2Fsites%2FVHACIDMO%2FCIDMO%5FFIS%2FIWS%2FICP%5FWG%2FIWS%2DHICP%2FFDER
